apiVersion: apps/v1
kind: Deployment
metadata:
  name: subrecommend
  namespace: user00
  labels:
    app: subrecommend
spec:
  selector:
    matchLabels:
      app: subrecommend
  replicas: 1
  template:
    metadata:
      name: subrecommend
      labels:
        app: subrecommend
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: subrecommend
          image: docker.io/hiondal/subrecommend:2.0.0
          imagePullPolicy: Always
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APPLICATION_NAME
              value: subrecommend
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: subride
          - configMapRef:
              name: subrecommend
          - secretRef:
              name: subride
          ports:
            - name: container-port
              containerPort: 18080
          resources:
            requests:
              cpu: 256m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          startupProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo > /dev/tcp/mysql-primary-headless/3306 >/dev/null 2 && curl -f http://config:18080/actuator/health/readiness"
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
